-- MySQL Workbench Synchronization
-- Generated: 2024-06-20 20:48
-- Model: New Model
-- Version: 1.0
-- Project: Name of the project
-- Author: Aluno

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

ALTER SCHEMA trabalho1  DEFAULT CHARACTER SET utf8  DEFAULT COLLATE utf8_general_ci ;

ALTER TABLE trabalho1.Aluno 
DROP FOREIGN KEY fk_Aluno_professor;

ALTER TABLE trabalho1.professor 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE trabalho1.Aluno 
CHARACTER SET = utf8 , COLLATE = utf8_general_ci ;

ALTER TABLE trabalho1.Aluno 
ADD CONSTRAINT fk_Aluno_professor
  FOREIGN KEY (professor_idprofessor)
  REFERENCES trabalho1.professor (idprofessor)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
